create table if not exists users (
    id bigint generated by default as identity primary key,
    username varchar(64) not null unique,
    password_hash varchar(255) not null,
    role varchar(32) not null
);
create table if not exists bookings (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    room_id bigint,
    status varchar(16) not null,
    start_date date,
    end_date date,
    request_id varchar(64) not null unique
);
