create table if not exists hotels (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    city varchar(255)
);

create table if not exists rooms (
    id bigint generated by default as identity primary key,
    hotel_id bigint not null,
    number varchar(64),
    available boolean not null default true,
    times_booked int not null default 0
);

create table if not exists room_holds (
    id bigint generated by default as identity primary key,
    room_id bigint not null,
    request_id varchar(64) not null unique,
    start_date date not null,
    end_date date not null,
    status varchar(16) not null
);

create index if not exists idx_room_dates on room_holds(room_id, start_date, end_date);
